---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "0958d61020835b9707536cc0525344fc30a764dd"
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
    fabric8.io/git-branch: "release-v2.2.297"
    fabric8.io/build-id: "4"
    fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/0958d61020835b9707536cc0525344fc30a764dd"
    fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/4"
  labels:
    provider: "fabric8"
    project: "elasticsearch"
    version: "2.2.297"
    group: "io.fabric8.devops.apps"
  name: "elasticsearch-masters"
spec:
  clusterIP: "None"
  ports:
  - name: "discovery"
    port: 9300
    protocol: "TCP"
    targetPort: 9300
  selector:
    project: "elasticsearch"
    provider: "fabric8"
    group: "io.fabric8.devops.apps"
