---
name: "elasticsearch"
home: "http://fabric8.io/elasticsearch/"
sources:
- "http://github.com/fabric8io/fabric8-devops/elasticsearch"
version: "2.2.297"
description: "[elasticsearch](http://elasticsearch.com/) provides distributed RESTful\
  \ search and analytics"
maintainers:
- name: "Fabric8 Development Team"
  email: "fabric8@googlegroups.com"
icon: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/elasticsearch/src/main/fabric8/icon.png"
